DemoDirectMvcBackend/Controllers/OlapAnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using RadarSoft.RadarCube.Web.Mvc;

namespace Controllers
{
    public class OlapAnalysisController : Controller
    {
        public SamplesModel SampleModel { get; set; }
        public ViewResult Index()
        {
            SampleModel = new SamplesModel();
            return View(SampleModel);
        }

        [AjaxOnly]
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult CallbackHandler()
        {
            var model = new ROlapSamplesModel();
            return Json(model.OlapAnalysis.DoCallback(), JsonRequestBehavior.DenyGet);
        }

        public ViewResult ChangeSkin(string skin)
        {
            SampleModel = new ROlapSamplesModel(Samples.GettingStarted);
            SampleModel.Skin = skin;
            return View("Index", SampleModel);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public BinaryStreamResult ExportHandler()
        {
            var sm  = new ROlapSamplesModel();
            SampleModel = sm;
            return sm.OlapAnalysis.DoExport();
        }


        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult PaintTrend()
        {
            return new ImageStreamResult(); 
        }
    }
}

DemoDirectMvcBackend/Views/Shared/PartialSkins.cshtml
@using RadarSoft.RadarCube.Common
@model Models.SamplesModel
<ul class="dropdown-menu">
@{
    var skins = Enum.GetValues(typeof(RadarSoft.RadarCube.Web.Skins)).Cast<RadarSoft.RadarCube.Web.Skins>().ToList();
    foreach (var skin in skins)
    {
        var description = RadarUtils.GetDescription(skin);
        var value = skin.ToString();
        var activeClass = value == Model.Skin ? "selected-item" : "";
        <li class="@activeClass">
            @Html.ActionLink(@description, "ChangeSkin", "OlapAnalysis", new { skin = @value }, null)
        </li>
    }
}
</ul>

DemoDirectMvcBackend/Views/Shared/_Layout.cshtml
@model Models.SamplesModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@Model.Product</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="http://radar-soft.com/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="http://radar-soft.com/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="http://radar-soft.com/favicon-16x16.png" sizes="16x16">
    <link rel="mask-icon" href="http://radar-soft.com/safari-pinned-tab.svg" color="#5584b1">
    <link href="~/Content/css/jquery.contextMenu.min.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap-treeview.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/css/vs.css" rel="stylesheet" />
    <link href="~/Content/css/samples.css" rel="stylesheet" />

    <script src="~/Content/js/jquery.min.js"></script>
    <script src="~/Content/js/jquery.ui.position.min.js"></script>
    @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>*@
    <script src="~/Content/js/tether.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/bootstrap-treeview.js"></script>
    <script src="~/Content/js/jquery.contextMenu.js"></script>
    <script src="~/Content/js/highlight.pack.js"></script>

    <link href="~/Content/rsolap/css/@(Model.Skin).RadarSoft.RadarCube.jquery-ui.css" rel="stylesheet" />
<!-- RadarCube debug -->
    @*<link href="~/Content/rsolap/css/RadarSoft.RadarCube.jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/rsolap/css/RadarSoft.RadarCube.jquery.treeview.css" rel="stylesheet" />
    <link href="~/Content/rsolap/css/jquery.treegrid.css" rel="stylesheet" />
    <link href="~/Content/rsolap/css/spectrum.css" rel="stylesheet" />
    <link href="~/Content/rsolap/css/jqPropertyGrid.css" rel="stylesheet" />

    <script src="~/Content/rsolap/RadarSoft.RadarCube.jquery.js"></script>
    <script src="~/Content/rsolap/RadarSoft.RadarCube.jquery-ui.js"></script>
    <script src="~/Content/rsolap/spectrum.js"></script>
    <script src="~/Content/rsolap/jqPropertyGrid.js"></script>
    <script src="~/Content/rsolap/jquery.treegrid.js"></script>
    <script src="~/Content/rsolap/RadarSoft.RadarCube.jquery.treeview.js"></script>
    <script src="~/Content/rsolap/rsMvcOlapAnalysis.js"></script>*@
    <!-- RadarCube debug end-->

    <!-- RadarCube production -->
    <link href="~/Content/rsolap/css/rsMvcOlapAnalysis.all.min.css" rel="stylesheet" />
    <script src="~/Content/rsolap/rsMvcOlapAnalysis.all.min.js"></script>
    <!-- RadarCube production end-->

    <!-- Angular2 Code -->
    <base href="/">
    <!-- Angular2 Code end-->
</head>
<body>
    <form id="client_postback" method="POST"></form>
    <div class="wrapper">
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">
                <a href="http://radar-soft.com/" class="navbar-brand">
                    <img src="~/Content/images/logo.png" />
                </a>
                <!--<h3>RadarCube HTML for ASP.NET Web Forms</h3>-->
                <!--<img src="RadarCube_Demo/logo.png">-->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Themes<span class="caret"></span></a>
                        @Html.Partial("PartialSkins")
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" style="padding:20px" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Demos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="http://aspnet-webforms.demos.radar-soft.com/">RadarCube for ASP.NET Web Forms</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <a href="http://silverlight.demos.radar-soft.com/">RadarCube for Silverlight</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>

        @RenderBody()
    </div>
    <div class="push"></div>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="footer-logo" style="height:50px;">
                        <a href="https://www.radar-soft.com/"><img src="Content/images/brand.png"></a>
                    </div>
                    <div style="margin-bottom:15px; margin-top:15px;">
                        <p style="color:#6096be">Follow us</p>
                        <a title="Facebook" href="https://www.facebook.com/rstrend/" target="_blank">
                            <img style="width:26px; height:26px; margin-right:10px;" src="Content/images/facebook.svg">
                        </a>
                        <a title="Vkontakte" href="https://vk.com/radarsoft" target="_blank">
                            <img style="width:26px; height:26px; margin-right:10px;" src="Content/images/vk.svg">
                        </a>
                        <a title="Twitter" href="https://twitter.com/RadarCube" target="_blank">
                            <img style="width:26px; height:26px; margin-right:10px;" src="Content/images/twitter.svg">
                        </a>
                        <a title="YouTube" href="https://www.youtube.com/channel/UCc6pBVYo7Sy7Gm5y1RfciqQ" target="_blank">
                            <img style="width:26px; height:26px; margin-right:10px;" src="Content/images/youtube.svg">
                        </a>
                    </div>
                </div>
                <div class="col-md-3">
                    <dl class="footer-nav">
                        <dt class="nav-title">RESOURCES</dt>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/news">News</a></dd>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/partnership">Partnership</a></dd>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/discounts">Discounts and Promotions</a></dd>
                        <dd class="nav-item"><a href="http://olaponline.radar-soft.com/" target="_blank">Online demo</a></dd>
                        <dd class="nav-item"><a href="http://support.radar-soft.net/" target="_blank">Helpdesk</a></dd>
                        <dd class="nav-item"><a href="http://support.radar-soft.net/index.php?/Knowledgebase/List" target="_blank">Knowledgebase</a></dd>
                        <dd class="nav-item"><a href="http://support.radar-soft.net/index.php?/Tickets/Submit" target="_blank">Submit support tickets</a></dd>
                    </dl>
                </div>
                <div class="col-md-3">
                    <dl class="footer-nav" id="product-list">
                        <dt class="nav-title">PRODUCTS</dt>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/products/radarcube-asp-net-web-forms">RadarCube for ASP.NET Web Forms</a></dd>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/products/radarcube-asp-net-mvc">RadarCube for ASP.NET MVC</a></dd>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/products/radarcube-windows-forms">RadarCube for Windows Forms</a></dd>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/products/radarcube-wpf">RadarCube for WPF</a></dd>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/products/hiercube-vcl">HierCube for VCL</a></dd>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/products/radarcube-vcl">RadarCube for VCL</a></dd>
                    </dl>
                </div>
                <div class="col-md-3">

                    <dl class="footer-nav">
                        <dt class="nav-title">CONTACTS</dt>
                        <dd class="nav-item"><a href="https://www.radar-soft.com/about">About Radar-Soft</a></dd>
                        <dd class="nav-item"><strong>Support:</strong> <a href="mailto:info@radar-soft.com" target="_blank">info@radar-soft.com</a></dd>
                        <dd class="nav-item"><strong>Sales:</strong> <a href="mailto:sales@radar-soft.com" target="_blank">sales@radar-soft.com</a></dd>
                        <dd class="nav-item">USA +1 206 965 8071</dd>
                        <dd class="nav-item">UK  +44 0121 288 2140</dd>
                    </dl>
                </div>

            </div>
            <div class="footer-copyright text-center">© 2005-2017 Radar-Soft, L.L.C. All rights reserved.</div>
        </div>
    </footer>

<script async src='https://www.google-analytics.com/analytics.js'></script>
<script src="~/Content/js/autotrack.js"></script>

@* Production *@
@*<script type="text/javascript" src="~/app-prod/inline.bundle.js"></script>
    <script type="text/javascript" src="~/app-prod/polyfills.bundle.js"></script>
    <script type="text/javascript" src="~/app-prod/vendor.bundle.js"></script>
    <script type="text/javascript" src="~/app-prod/main.bundle.js"></script>*@
@* Debug *@
<script src="node_modules/core-js/client/shim.min.js"></script>
<script src="node_modules/zone.js/dist/zone.js"></script>
<script src="node_modules/reflect-metadata/Reflect.js"></script>
<script src="node_modules/systemjs/dist/system.src.js"></script>
<script src="systemjs.config.js"></script>
<script>
    System.import('app').catch(function (err) { console.error(err); });
</script>
</body>
</html>